name: Go Multi-Platform Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release Go Binary for Multiple Platforms
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build Go Binary
        run: |
          mkdir -p dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/alphalab-${{ matrix.goos }}-${{ matrix.goarch }}

      # Ensure the binary is executable (Unix systems)
      - name: Set Executable Permissions
        run: chmod +x dist/alphalab-${{ matrix.goos }}-${{ matrix.goarch }}

      # List the files to confirm permissions
      - name: List Files for Debugging
        run: ls -la dist/

      # Create the GitHub Release and Upload Built Binaries as Assets
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
