name: Go Multi-Platform Build and Release 

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release Go Binary for Multiple Platforms
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build Go Binary with Static Linking
        run: |
          mkdir -p dist
          # Force static build and ensure proper permissions on Unix
          CGO_ENABLED=0 GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -a -ldflags '-extldflags "-static"' -o dist/alphalab-${{ matrix.goos }}-${{ matrix.goarch }}
          
          # Ensure Unix executables are marked executable
          if [[ "${{ matrix.goos }}" != "windows" ]]; then
            chmod +x dist/alphalab-${{ matrix.goos }}-${{ matrix.goarch }}
          fi

      - name: List Built Files for Debugging
        run: ls -la dist/

      # Release the binaries as GitHub release assets
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
